-- begin INDORSOFTKUBA_PROJECT_EMPLOYEE_LINK
alter table INDORSOFTKUBA_PROJECT_EMPLOYEE_LINK add constraint FK_PROEMP_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references INDORSOFTKUBA_EMPLOYEE(ID)^
alter table INDORSOFTKUBA_PROJECT_EMPLOYEE_LINK add constraint FK_PROEMP_ON_PROJECT foreign key (PROJECT_ID) references INDORSOFTKUBA_PROJECT(ID)^
-- end INDORSOFTKUBA_PROJECT_EMPLOYEE_LINK
